bhargavieppagunta/TinyBlogger

assets/css/style.css
index.php
single.php

This page contains the content of particular post. For now it's just the outline for a single page.

Designing a Single blog post

---

app/includes/header.php
assets/css/style.css
login.php
register.php

This a design for Login and Register pages, Where user and admin will be able to login and register themselves from.

Adding Login and Register pages

---

forgot_password.php
login.php
password_message.php
reset_password.php

This is a design of forgot password, reset password and password reset message. Connect forgot password to Login.php to navigate easily.

Adding password related pages

---

index.php
single.php

The images are linked to their respective blog posts

Linking media to posts

---

about.php
app/includes/footer.php
app/includes/header.php
events.php
forgot_password.php
index.php
login.php
password_message.php
path.php
register.php
single.php

Setup Common path for easy navigation between pages, with a common path.

setting up common path

---

admin/dashboard.php
assets/css/admin.css

Design of Admin Dashboard, styling for Admin Panel.

Implementing admin dashboard

---

admin/dashboard.php
app/includes/adminHeader.php
app/includes/adminSidebar.php
assets/css/admin.css

Enhancing the admin page with a header and a sidebar

Adding Header and Sidebar to admin page

---

admin/posts/create.php
admin/posts/edit.php
admin/posts/index.php
admin/topics/edit.php

Have developed and added create and edit for posts page.

Implemented create and edit pages for posts page.

---

admin/users/index.php
app/includes/adminSidebar.php

This adds index page functionality for the users, where users can add and modify themselves.

Implementing index pages for users

---

admin/posts/index.php
admin/topics/index.php
admin/users/create.php
admin/users/edit.php
admin/users/index.php

Developing a user-friendly interface for creating and editing user profiles.

Developing-Create- and-Edit-Page-for-Users

---

app/database/connect.php

This functionality  is added to set up a PHPMyAdmin database, including the creation of necessary tables. It ensures efficient data management and retrieval within the application.

Added PHPMyAdmin DB setup and table creation

---

app/database/db.php

This code contains complex queries and functionalities to retrieve data

 Develop Complex Database Queries for Data Retrieval Functionalities

---

app/helpers/formErrors.php
app/helpers/middleware.php
app/helpers/validatePost.php
app/helpers/validateTopic.php
app/helpers/validateUser.php

This code contains Form data validation and error handlings which ensure accurate input and user-friendly error messages for seamless interaction.

Form Data Validation and Error Handling Implementation

---

admin/posts/create.php
admin/posts/edit.php
admin/posts/index.php
admin/topics/create.php
admin/topics/edit.php
admin/topics/index.php
admin/users/create.php
admin/users/edit.php
admin/users/index.php

This code contains code changes of Retrieving Data of posts, topics, users in the Admin dashboard directly from Database so that it’s easier for navigation and data redundancy.

Implemented admin dashboard optimization.

---

app/controllers/posts.php
app/controllers/topics.php
app/controllers/users.php
app/includes/messages.php

This code contains changes of functionalities to post data into database and navigation between in a seamless manner so that it will  not duplicates and normalization into the database.

Implemented normalization of database

---

about.php
admin/posts/create.php
admin/posts/edit.php
admin/posts/index.php
admin/topics/create.php
admin/topics/edit.php
admin/topics/index.php
admin/users/create.php
admin/users/edit.php
admin/users/index.php
events.php
forgot_password.php
index.php

The code contains changes regarding including the controllers to all the admin panel pages and retrieving data to index page so that user can seamless access the posts which comes directly from the database.

Integrate Admin Controllers & Retrieve Index Data

---

admin/dashboard.php
app/includes/adminHeader.php
app/includes/header.php
login.php
logout.php
password_message.php
register.php
reset_password.php
single.php

This code contains changes of retrieving data from DB for single.php, login, register. and also logout.php has been added to logout from their account for both users and admins.

Optimize database integration and user authentication

---

app/controllers/emailController.php
app/controllers/users.php
app/helpers/middleware.php
app/includes/welheader.php
index.php
welcome.php

This contains code related to User Verification when they register and forgot password, to retrieve if any user forgets their password.

Developed user authentication and password recovery.

---

app/controllers/emailController.php
app/controllers/users.php
app/includes/header.php
otpVerify.php

This is an implementation of OTP login for Users and Admins for secure access towards the application and avoid unauthorized access using just password.

Implement admin Multi-Factor Authentication

---

about.php
admin/dashboard.php
admin/posts/create.php
admin/posts/edit.php
admin/posts/index.php
admin/topics/create.php
admin/topics/edit.php
admin/topics/index.php
admin/users/create.php
admin/users/edit.php
admin/users/index.php
assets/js/scripts.js
events.php
forgot_password.php
index.php
login.php
otpVerify.php
password_message.php
register.php
reset_password.php
single.php
welcome.php

This code explains JavaScript and Font Awesome scripts have been added for better user experiences and Admin easy can easily Write posts using ClassicEditor.

Integrate JavaScript and Font Awesome Scripts for body of posts
